baseURL: https://pinnotes.github.io/ # pinnotes.github.io
languageCode: en-us
title: PinNotes

module:
  imports:
    - path: github.com/imfing/hextra

# Parse Git commit
enableGitInfo: false

enableRobotsTXT: true
enableEmoji: true
hasCJKLanguage: true

services:
 googleAnalytics:
    ID: G-4VREMGGN3N

taxonomies:
  tag: tags
  category: categories
  author: authors
  series: series

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

related:
  includeNewer: false
  indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ""
    toLower: false
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 0
    name: date
    pattern: ""
    toLower: false
    type: basic
    weight: 10
  - applyFilter: false
    cardinalityThreshold: 0
    name: tags
    pattern: ""
    toLower: false
    type: basic
    weight: 80
  threshold: 80
  toLower: false

outputs:
  home: [HTML]
  page: [HTML]
  section: [HTML, RSS]

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block: [['\[', '\]'], ['$$', '$$']]
          inline: [['\(', '\)']]
        enable: true

enableInlineShortcodes: true

menu:
  main:
    # - name: Courses
      # pageRef: /courses
      # weight: 1//////////////////////////////
    - name: Exercises
      pageRef: /exercises
      weight: 3
    - name: Notes
      pageRef: /notes
      weight: 2
    - name: IIT
      pageRef: /iit-madras
      weight: 4
    # - name: Assignments
      # pageRef: /assignments
      # weight: 5
    # - name: Examples
      # pageRef: /examples
      # weight: 6
    - name: Blog
      pageRef: /blog
      weight: 7
    - name: Search
      weight: 10
      params:
        type: search
    # - name: GitHub
      # weight: 6
      # url: "https://github.com/imfing/hextra"
      # params:
      #   icon: youtube

sidebar:
     - identifier: more
       name: References
       params:
         type: separator
       weight: 1
     - identifier: courses
       name: "Courses"
       url: "/courses"
       weight: 2
     - identifier: iit-madras
       name: "IIT Madras"
       url: "/iit-madras"
       weight: 3
    #  - identifier: examples
      #  name: "Examples"
      #  url: "/examples"
      #  weight: 4
docs:
    - name: "Introduction"
      url: "/docs/"
      weight: 10
    - name: "Getting Started"
      url: "/docs/getting-started/"
      weight: 20
    - name: "Installation"
      url: "/docs/installation/"
      weight: 30


params:
  # description
  description: PinNotes is your go-to platform for accessing high-quality academic notes and practice questions across a wide range of subjects. Whether you’re preparing for exams, brushing up on concepts, or seeking targeted revision, PinNotes helps you organize, highlight, and master your studies with ease. With intuitive navigation and a growing library of resources, PinNotes is designed to support students at every stage of their educational journey—making learning efficient, effective, and engaging.
 
  editURL:
    enable: false
    base: "https://github.com/pinnotes/your-repo/edit/main"

  theme:
    # light | dark | system
    default: system
    displayToggle: true

  # Display the last modification date
  displayUpdatedDate: false
  dateFormat: "January 2, 2006"

  page:
    # full (100%), wide (90rem), normal (1280px)
    width: full
  
  highlightCurrentMenuArea: true
  smartTOC: true
  smartTOCHideUnfocusedChildren: true

  # Sidebar
  docs:
    sidebarTitle: "Documentation"
    sidebarIcon: "book"
    sidebarIconColor: "#000000"

  # navbar          
  navbar:
    displayTitle: false
    displayLogo: true
    logo:
      path: images/favicon.svg # static - images folder
      dark: images/favicon-dark.svg
      link: /
      width: 40
      height: 20


  footer:
    enable: false
    displayCopyright: true
    displayPoweredBy: false
    width: normal

  # Search
  search:
    enable: true
    type: flexsearch

    flexsearch:
      # index page by: content | summary | heading | title
      index: content
    # ...
    flexsearch:
      # full | forward | reverse | strict 
      tokenize: forward

  blog:
    list:
      displayTags: true
      # date | lastmod | publishDate | title | weight
      sortBy: weight
      sortOrder: desc # or "asc"
      image: images/git.jpg

    article:
      displayPagination: false
      showRelatedContent: true
      relatedContentLimit: 8
  
  
  courses:
    list:
      displayTags: true
      # date | lastmod | publishDate | title | weight
      sortBy: date
      sortOrder: desc # or "asc"
      image: images/green.jpg
      gradientCard: false

  notes:
    list:
      displayTags: true
      # date | lastmod | publishDate | title | weight
      sortBy: date
      sortOrder: desc # or "asc"

  highlight:
    copy:
      enable: true
      # hover | always
      display: hover
            


